---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: core-services
  annorations:
    maintained: CloudInfra
spec:
  releaseName: flux
  chart:
    name: flux
    repository: https://charts.fluxcd.io
    version: "1.4.1"
    wait: false
  values:
    dashboard:
      enabled: false
    syncGarbageCollection:
      enabled: true
    git:
      branch: git@github.com:Lightricks/eks-core-services.git
      readonly: true
      path: "k8s,core-services"
      pollInterval: 1m
      secretName: flux-git-deploy
      url: master
    image:
      repository: docker.io/fluxcd/flux
    rbac:
      create: false
    serviceAccount:
      create: false
      name: ops-flux
    sync:
      state: secret
    prometheus:
      serviceMonitor:
        create: false
    manifestGeneration: true