---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    name: ops-flux
  name: ops-flux
  namespace: core-services
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    name: ops-flux
  name: ops-flux
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
  - nonResourceURLs: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    name: ops-flux
  name: ops-flux
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ops-flux
subjects:
  - kind: ServiceAccount
    name: ops-flux
    namespace: core-services
