apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: core-services

spec:
  targetNamespace: kube-system
  chart:
    name: sealed-secrets
    repository: https://kubernetes-charts.storage.googleapis.com
    wait: True
    version: 1.10.3
  values:
    namespace: kube-system